### ISSUE TITLE
Cookie is not visible in DevTools

### ISSUE THREAD

**Issue by kwiat1990** [christopher-talke/talke-dev#2]
Hi,

I have copied your code and it seems to work. In network tab there is a `set-cookie` property with the right options (in response object). The same I can see when I'm using Postman. But after I successfully log-in, the cookie isn't visible under `Application -> Cookies` tab.

**Comment by christopher-talke** [comment]
Hi @kwiat1990,

This is because postman will have an `withCredentials` header in the http request (see below example from code I had written in the past).

```js
const login = async () => {
    await axios
      .post(
        `${constants.API}/auth/local`,
        {
          identifier: username,
          password,
        },
        {
          withCredentials: true, // <-- This is a critical part of the HTTP Request, if you are not using axios, please refer to the docs of your http client for a 'withCredentials' header
        }
      )
      .then(() => {
        alert({ type: 'success', message: 'Logged in successfully!' });
        setTimeout(getUser, 1000);
      })
      .catch((e) => {
        alert({ type: 'error', message: 'Your username or password was incorrect, please try again.' });
      });
  };
```

Without this, the cookie will not be accepted by the browser once a reply is recieved.
